/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "GradleCppTest.h"
#include "JNICode.h"

std::string GradleCppTest::Greeter::greeting() {
    return std::string("Hello, World!");
}

extern "C" {
JNIEXPORT jint JNICALL Java_JNICode_doThing
  (JNIEnv *, jclass) {
      return 0;
  }

  JNIEXPORT jint JNICALL Java_JNICode_doThing23
  (JNIEnv *, jclass) {
      return 0;
  }
}
