/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef GRADLECPPTEST_H
#define GRADLECPPTEST_H

#ifdef _WIN32
#define GRADLECPPTEST_EXPORT_FUNC __declspec(dllexport)
#else
#define GRADLECPPTEST_EXPORT_FUNC
#endif

#include <string>

namespace GradleCppTest {
    class Greeter {
        public:
        std::string GRADLECPPTEST_EXPORT_FUNC greeting();
    };
}

#endif
